/**
 * API client for the ASD Detection Backend.
 *
 * Security responsibilities of this module:
 *   * Inject the current Firebase ID token on every request as
 *     `Authorization: Bearer <token>`. The token is fetched fresh from
 *     `auth().currentUser.getIdToken()` so a recently-refreshed token is
 *     always preferred.
 *   * Refuse to send requests with no token to protected endpoints
 *     (anything under `/api/`). Public endpoints like `/healthz` are
 *     allowed.
 *   * On `401`, force a token refresh and retry exactly once. This
 *     handles the common case where the cached token has expired.
 *   * Surface backend errors via the standardised envelope
 *     (`{ error: { code, message, request_id } }`) without leaking
 *     server-side details to the rest of the app.
 *
 * For local development on Android (both emulator and real device):
 *   1. Start the backend on your computer: poetry run fastapi dev app/main.py
 *   2. Either rely on the emulator default 10.0.2.2:8000, or run
 *      `adb reverse tcp:8000 tcp:8000` and override apiBaseUrl in
 *      `src/config/runtime.local.ts` to `http://localhost:8000`.
 *
 * For iOS simulator: localhost works directly.
 *
 * For production, override `apiBaseUrl` and set `requireHttps: true` in
 * `src/config/runtime.generated.ts` (generated by your build pipeline).
 */

import auth from '@react-native-firebase/auth';

import { API_BASE_URL, ENABLE_API_DEBUG_LOGS } from '../config/env';

interface RequestOptions {
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  body?: unknown;
  headers?: Record<string, string>;
  timeoutMs?: number;
  /**
   * If true the request is sent without an Authorization header.
   * Reserved for `/healthz`-style probes; defaults to false.
   */
  skipAuth?: boolean;
}

class ApiError extends Error {
  status: number;
  detail: string;
  /** Standardised error code from the backend envelope (e.g. `payload_too_large`). */
  code?: string;
  /** Per-request correlation ID returned by the backend on 5xx. */
  requestId?: string;

  constructor(status: number, detail: string, code?: string, requestId?: string) {
    super(detail);
    this.name = 'ApiError';
    this.status = status;
    this.detail = detail;
    this.code = code;
    this.requestId = requestId;
  }
}

async function getIdTokenOrThrow(forceRefresh: boolean): Promise<string> {
  const user = auth().currentUser;
  if (!user) {
    throw new ApiError(401, 'You must sign in to continue.', 'unauthenticated');
  }
  try {
    return await user.getIdToken(forceRefresh);
  } catch (err) {
    throw new ApiError(
      401,
      'Could not refresh your session. Please sign in again.',
      'token_refresh_failed',
    );
  }
}

function isProtectedPath(path: string): boolean {
  // Anything under /api/* requires auth. /healthz, /readyz, / are public.
  return path.startsWith('/api/');
}

async function buildHeaders(
  path: string,
  extra: Record<string, string>,
  forceRefresh: boolean,
  skipAuth: boolean,
): Promise<Record<string, string>> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    Accept: 'application/json',
    ...extra,
  };
  if (!skipAuth && isProtectedPath(path)) {
    headers.Authorization = `Bearer ${await getIdTokenOrThrow(forceRefresh)}`;
  }
  return headers;
}

async function parseError(response: Response, fallbackStatus: number): Promise<ApiError> {
  let detail = `Request failed with status ${fallbackStatus}`;
  let code: string | undefined;
  let requestId: string | undefined;
  try {
    const body = await response.json();
    if (body && typeof body === 'object') {
      // New envelope: { error: { code, message, request_id } }
      const err = (body as any).error;
      if (err && typeof err === 'object') {
        if (typeof err.message === 'string') detail = err.message;
        if (typeof err.code === 'string') code = err.code;
        if (typeof err.request_id === 'string') requestId = err.request_id;
      } else if (typeof (body as any).detail === 'string') {
        // Legacy FastAPI shape — kept for compatibility with /healthz etc.
        detail = (body as any).detail;
      }
    }
  } catch {
    /* ignore JSON parse errors on error responses */
  }
  return new ApiError(fallbackStatus, detail, code, requestId);
}

async function request<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const { method = 'GET', body, headers = {}, timeoutMs = 60_000, skipAuth = false } = options;
  const url = `${API_BASE_URL}${path}`;

  const doFetch = async (forceRefresh: boolean): Promise<Response> => {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const resolvedHeaders = await buildHeaders(path, headers, forceRefresh, skipAuth);
      const fetchOptions: RequestInit = {
        method,
        headers: resolvedHeaders,
        signal: controller.signal,
      };
      if (body !== undefined) {
        fetchOptions.body = JSON.stringify(body);
      }
      if (ENABLE_API_DEBUG_LOGS) {
        // Never log the body — it can contain raw audio/image data and
        // would also drown the Metro console.
        console.log(`[api] ${method} ${path}`);
      }
      return await fetch(url, fetchOptions);
    } finally {
      clearTimeout(timeout);
    }
  };

  let response = await doFetch(false);

  // Retry once on 401 with a forced token refresh — handles the common
  // case where the cached token is moments past expiry.
  if (response.status === 401 && !skipAuth && isProtectedPath(path)) {
    response = await doFetch(true);
  }

  if (!response.ok) {
    throw await parseError(response, response.status);
  }

  return (await response.json()) as T;
}

export { request, ApiError, API_BASE_URL };
